public class brainstormnew2 {

   /* public static void brainstorm(){
        List<Account> accountList=new List<Account>();
        accountList=[select id,tick__c from Account limit 1000];
        
        List<Contact> conlist=new List<Contact>();
        conlist=[select id,accountid from Contact where accountid in: accountList];
        
         map<id,Account> mapName2=new map<id,Account>();
        
        for(Account acc:accountList){
            if(!mapName2.containsKey(acc.id)){
                mapName2.put(acc.id,acc);
            }
        }
        
         List<Opportunity> opportunityList=new List<Opportunity>();
        opportunityList=[select id,accountid from Opportunity where accountid in: accountList];
        
        List<OpportunityContactRole> ocrList=new List<OpportunityContactRole>();
        ocrList=[select id,contactid,opportunityid from OpportunityContactRole where opportunityid in: opportunityList];
         
        for(Id id1:mapName.keySet()){
             for(OpportunityContactRole ocr:ocrList){
                  
            }
        }
        
        }*/
    }