public class stringClass {

    public static void StringMethod(){
        String s='My name is Anthony Gonjalwes';
        System.debug(s);
        
        Date d=Date.newInstance(2020, 10, 12);
        System.debug(d);
        Time t=Time.newInstance(12, 30, 50, 10);
        System.debug(t);
        
        DateTime dt=DateTime.newInstance(2020,08,12,11,30,40);
        system.debug(dt);
         
        
       // Id i='123456789012abc';
       // System.debug(i);
      
      Blob b=Blob.valueOf('abc');
        System.debug(b);
        System.debug(b.toString());
   
    
    }
    
    
}