public class YoungAstronaut14 {
    /*
    public static void forYoung(){
        List<OrderItem> OrderItemList=new List<OrderItem>();
        OrderItemList=[select id,OrderId,Product2Id,Product2.Name,Order.name,taxRate__c from OrderItem];
        for(OrderItem ordr:OrderItemList){
            if(ordr.Product2.family=='Electronics')
            {
                ordr.taxRate__c=0.02;
            }
            
            else if(ordr.Product2.family=='FootWear')
            {
                ordr.taxRate__c=0.05;
            }
            
            else if(ordr.Product2.family=='Clothing')
            {
                ordr.taxRate__c=0.07;
            }
            
            ordr.finalRate__c=ordr.UnitPrice*ordr.Quantity*o.taxRate__c;
            
            system.debug(o.taxRate__c);
            system.debug(a.Family);
            System.debug(o.finalRate__c);
            
        }
        
    }
}*/
}