@isTest
public class Young10Test {
   /*  @isTest
    public static void forOpportunityTest(){
        Id oppRecordtypeId=Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('Shivam').getRecordTypeId(); 
        Opportunity op=new Opportunity();
        op.Name='abc';
        op.CloseDate=system.today();
        op.StageName='Qualification';
        op.RecordTypeId=oppRecordtypeId;
    
        Test.startTest();
        Young10.forOpportunity();
        Test.stopTest();
        
    }
*/
}